name: Deploy CLI NPM Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/cli/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        working-directory: packages/cli
        run: pnpm install --no-frozen-lockfile

      - name: Build @hypership/cli Package
        working-directory: packages/cli
        run: pnpm run build

      - name: Build hypership Package
        working-directory: packages/hypership
        run: pnpm run build

      - name: Publish @hypership/cli Package
        working-directory: packages/cli
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @hypership Package
        working-directory: packages/hypership
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
